
# flags.py

NATIONALITY_FLAGS = {
    "Argentina": "https://flagcdn.com/ar.svg",
    "Colombia": "https://flagcdn.com/co.svg",
    "Saudi Arabia": "https://flagcdn.com/sa.svg",
    "Spain": "https://flagcdn.com/es.svg",
    "Brazil": "https://flagcdn.com/br.svg",
    "Uzbekistan": "https://flagcdn.com/uz.svg",
    "Portugal": "https://flagcdn.com/pt.svg",
    "Korea, South": "https://flagcdn.com/kr.svg",
    "Peru": "https://flagcdn.com/pe.svg",
    "Mali": "https://flagcdn.com/ml.svg",
    "Nigeria": "https://flagcdn.com/ng.svg",
    "Poland": "https://flagcdn.com/pl.svg",
    "Eritrea": "https://flagcdn.com/er.svg",
    "Gabon": "https://flagcdn.com/ga.svg",
    "Egypt": "https://flagcdn.com/eg.svg",
    "Italy": "https://flagcdn.com/it.svg",
    "Angola": "https://flagcdn.com/ao.svg",
    "Morocco": "https://flagcdn.com/ma.svg",
    "Tunisia": "https://flagcdn.com/tn.svg",
    "Sweden": "https://flagcdn.com/se.svg",
    "Türkiye": "https://flagcdn.com/tr.svg",
    "North Macedonia": "https://flagcdn.com/mk.svg",
    "Netherlands": "https://flagcdn.com/nl.svg",
    "Bolivia": "https://flagcdn.com/bo.svg",
    "The Gambia": "https://flagcdn.com/gm.svg",
    "Romania": "https://flagcdn.com/ro.svg",
    "Algeria": "https://flagcdn.com/dz.svg",
    "Cameroon": "https://flagcdn.com/cm.svg",
    "Cape Verde": "https://flagcdn.com/cv.svg",
    "Canada": "https://flagcdn.com/ca.svg",
    "Iraq": "https://flagcdn.com/iq.svg",
    "Burkina Faso": "https://flagcdn.com/bf.svg",
    "France": "https://flagcdn.com/fr.svg",
    "Panama": "https://flagcdn.com/pa.svg",
    "England": "https://flagcdn.com/gb-eng.svg",  # unofficial
    "Bosnia-Herzegovina": "https://flagcdn.com/ba.svg",
    "Zambia": "https://flagcdn.com/zm.svg",
    "Uruguay": "https://flagcdn.com/uy.svg",
    "Greece": "https://flagcdn.com/gr.svg",
    "Austria": "https://flagcdn.com/at.svg",
    "Norway": "https://flagcdn.com/no.svg",
    "Curacao": "https://flagcdn.com/cw.svg",
    "Australia": "https://flagcdn.com/au.svg",
    "Jamaica": "https://flagcdn.com/jm.svg"
}
